### ISSUE TITLE
Test with `odo pipeline create` prototype

### ISSUE THREAD

**Issue by mnuttall** [rhd-gitops-example/services#18]
The `bootstrap` branch in https://github.com/rhd-gitops-example/odo shows how `odo pipelines bootstrap (init)` can be used to create a gitops repo that should be compatible with our `promote` verb. Check that this is still the case. Can we script a manual test for this?

**Comment by dibbles** [comment]
Notes: 

- installed binami-labs sealed secrets
- created a secret containing access token to access github (foo)
- ran `odo pipelines init --gitops-repo owner/repo --gitops-webhook-secret foo`

Results in the following creation

![Screenshot 2020-04-06 at 10 22 09](https://user-images.githubusercontent.com/22838162/78543369-7c54a580-77f0-11ea-838b-1e567dfb482c.png)

directories contain pre-configured yaml that can applied to the system, e.g an eventlistener for the repo specified on the odo command. There are 2 pipleines, one for dry run and one for "deploy from push" essentially a kubctl apply...

```
steps:
  - args:
    - apply
    - --dry-run=$(inputs.params.DRYRUN)
    - -n
    - $(inputs.params.NAMESPACE)
    - -k
    - $(inputs.params.PATHTODEPLOYMENT)
    command:
    - kubectl
    image: quay.io/redhat-developer/k8s-kubectl
    name: run-kubectl
    resources: {}
    workingDir: /workspace/source
```

Chatted with Kevin about this (because we were looking for the app/deployment structure to be created rather than the tekton artefacts), and he pointed me to a tool in his repo "manifestor" which takes a yaml input and outputs a directory structure akin to what was required.

- https://github.com/bigkevmcd/manifestor
- ran `manifestor bootstrap ./input-yaml ./outputdir`

for input:

```
environments:
  - name: development
    pipelines:
      integration:
        template: dev-ci-template
        binding: dev-ci-binding
      deployment:
        template: dev-cd-template
        binding: dev-cd-binding
    apps:
      - name: my-app-1
        services:
          - name: app-1-service-http
            source_url: https://github.com/myproject/myservice.git
          - name: app-1-service-metrics
      - name: my-app-2
        services:
          - name: app-2-service
  - name: staging
    apps:
      - name: my-app-1
        services:
          - name: app-1-service-http
  - name: production
    apps:
      - name: my-app-1
        services:
          - name: app-1-service-http
          - name: app-1-service-metrics
            config_repo:
              url: https://github.com/testing/testing
              ref: master
              path: config
```

output is:

![Screenshot 2020-04-06 at 10 33 11](https://user-images.githubusercontent.com/22838162/78544414-05201100-77f2-11ea-91d1-23b59fcbe5d3.png)

sample expanded output:

![Screenshot 2020-04-06 at 10 35 52](https://user-images.githubusercontent.com/22838162/78544661-65af4e00-77f2-11ea-8557-b7400c136796.png)
